# -*- coding: utf-8 -*-
"""
Generate lib/content/copy.da.ts from Bjørn's macro-enabled workbook.

History of this file's source, because it has moved twice:

  1. The .xlsx Mathieu sent -- a serviceable machine draft.
  2. A PDF print of Bjørn's own workbook, which rewrote 51 strings into
     idiomatic Danish. Parsed out of the PDF because that was all we had.
  3. This .xlsm, the workbook that PDF was printed from, now with further
     edits. Reading the spreadsheet directly removes the PDF-parsing step and
     everything that could go wrong in it.

Two traps in this workbook:

  * Its Let's Talk sheet is named "LETS TALK", without the apostrophe the
    .xlsx uses. Matching on one spelling silently drops 97 strings, so both
    spellings are accepted.
  * It is macro-enabled, so it needs keep_vba=True.

Every row's English is checked against the published English before its Danish
is used; a mismatch means the row is not the row we think it is, and the run
aborts rather than attach Danish to the wrong sentence.
"""
import io
import os
import re

import openpyxl

SRC = os.path.join(
    r"C:\Users\Abbas\OneDrive\Desktop\noman",
    "REFUGE61_Website_V3_FR_corrige_CHANGES_MAJ.xlsm",
)
OUT = "lib/content/copy.da.ts"
REFERENCE = "lib/content/copy.fr.ts"  # for its `en` field and page names

# Sheet name -> the page slug used in the generated file. Both spellings of
# the Let's Talk sheet are listed; the workbooks disagree.
SHEET_PAGE = {
    "HOME": "home",
    "THE LODGE": "lodge",
    "PRACTICAL INFO": "practical",
    "LET'S TALK": "letsTalk",
    "LETS TALK": "letsTalk",
    "NAVIGATION": "nav",
}

ENTRY = re.compile(
    r'(T\d{3}): \{\s*page: "([^"]*)",\s*type: "((?:[^"\\]|\\.)*)",'
    r'\s*en: "((?:[^"\\]|\\.)*)",\s*tr: "((?:[^"\\]|\\.)*)"',
    re.S,
)


def norm(s):
    return re.sub(r"\s+", " ", (s or "")).strip()


def unescape(s):
    return s.replace('\\"', '"').replace("\\n", "\n").replace("\\\\", "\\")


def reference():
    """{T-id: (page, type, english)} from the French module, which mirrors
    the JSX and is regenerated from the same spreadsheet family."""
    src = io.open(REFERENCE, encoding="utf-8").read()
    return {
        m.group(1): (m.group(2), unescape(m.group(3)), unescape(m.group(4)))
        for m in ENTRY.finditer(src)
    }


def esc(t):
    return t.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def main():
    wb = openpyxl.load_workbook(SRC, keep_vba=True, data_only=True)
    ref = reference()

    rows, mismatched, unknown = [], [], []
    for name in wb.sheetnames:
        page = SHEET_PAGE.get(name.upper())
        if not page:
            continue
        for r in wb[name].iter_rows(min_row=4, values_only=True):
            if not r or not r[0]:
                continue
            tid = str(r[0]).strip()
            if not re.fullmatch(r"T\d{3}", tid):
                continue
            da = norm(r[4]) if len(r) > 4 else ""
            if not da:
                continue
            if tid not in ref:
                unknown.append(tid)
                continue
            ref_page, ref_type, ref_en = ref[tid]
            if norm(r[2]) != norm(ref_en):
                mismatched.append(tid)
                continue
            rows.append((tid, ref_page, ref_type, ref_en, da))

    if mismatched:
        print("ABORTING -- English mismatch on %d row(s): %s"
              % (len(mismatched), ", ".join(mismatched[:12])))
        raise SystemExit(1)
    if unknown:
        print("note: %d Danish row(s) have no published English and were "
              "skipped: %s" % (len(unknown), ", ".join(unknown[:12])))

    out = io.StringIO()
    out.write('''// Danish copy.
//
// Generated by _scripts/i18n/gen_copy_da.py from the .xlsm Bjørn maintains.
// His Danish is a rewrite, not a translation of the machine draft that first
// went live -- he replaced serviceable Danish with idiomatic Danish.
//
// Every row was checked against the published English before being written,
// so a Danish string cannot end up attached to the wrong sentence.
//
// Terms & Conditions are absent here: that page has its own module,
// lib/content/terms.ts.
//
// DO NOT EDIT BY HAND -- regenerate from the spreadsheet instead.

export type CopyEntry = {
  readonly page: string;
  readonly type: string;
  readonly en: string;
  readonly tr: string;
};

export const COPY_DA: Readonly<Record<string, CopyEntry>> = {
''')
    for tid, page, typ, en, da in rows:
        out.write('  %s: {\n    page: "%s",\n    type: "%s",\n    en: "%s",\n    tr: "%s",\n  },\n'
                  % (tid, page, esc(typ), esc(en), esc(da)))
    out.write('''};

/** Look up the approved Danish for an exact English string. */
export const DA_BY_ENGLISH: ReadonlyMap<string, string> = new Map(
  Object.values(COPY_DA).map((e) => [e.en, e.tr]),
);
''')
    io.open(OUT, "w", encoding="utf-8").write(out.getvalue())
    print("%d Danish strings -> %s" % (len(rows), OUT))


if __name__ == "__main__":
    main()
