# -*- coding: utf-8 -*-
"""
Regenerate lib/content/copy.fr.ts and the snapshot it was built from.

Point SRC at the client's newest French spreadsheet and run. The snapshot
(_client_fr.json) is committed so the next revision can be diffed against what
is actually live -- see diff_fr.py -- rather than against whichever file
happens to be in Downloads.

Run: python _scripts/i18n/gen_copy_fr.py
"""
import io
import json
import os
import re

import openpyxl

SRC = os.path.join(
    r"C:\Users\Abbas\OneDrive\Desktop\noman",
    "REFUGE61_Website_V2_EN_FR_DA_FR_corrige.xlsx",
)
SNAPSHOT = "_scripts/i18n/_client_fr.json"
OUT = "lib/content/copy.fr.ts"

SHEET_PAGE = {
    "HOME": "home",
    "THE LODGE": "lodge",
    "PRACTICAL INFO": "practical",
    "LET'S TALK": "letsTalk",
    "TERMS": "terms",
    "NAVIGATION": "nav",
}


def clean(s):
    # The client types in Word; runs of whitespace and stray double spaces come
    # through with the text ("pendant  l'hiver 2027").
    return re.sub(r"\s+", " ", (s or "").strip())


def read():
    wb = openpyxl.load_workbook(SRC)
    sheets, rows = {}, []
    for name, page in SHEET_PAGE.items():
        if name not in wb.sheetnames:
            continue
        got = []
        for r in wb[name].iter_rows(min_row=4, values_only=True):
            if not r or not r[0]:
                continue
            entry = {
                "id": str(r[0]).strip(),
                "type": clean(r[1]),
                "en": clean(r[2]),
                "fr": clean(r[3]),
            }
            got.append(entry)
            if entry["en"] and entry["fr"]:
                rows.append((page, entry))
        sheets[name] = got
    return sheets, rows


def esc(t):
    return t.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def main():
    sheets, rows = read()
    json.dump({"sheets": sheets}, io.open(SNAPSHOT, "w", encoding="utf-8"),
              ensure_ascii=False, indent=1)

    out = io.StringIO()
    out.write('''// French copy, approved by the client.
// Generated by _scripts/i18n/gen_copy_fr.py from his French spreadsheet.
//
// Keys are the T-ids from docs/_website-copy-EN.md, assigned by
// _scripts/extract-copy.mjs in document order. `en` is kept alongside `fr` so
// a string can be located in the JSX by exact match on the English.
//
// Terms & Conditions are absent here: that page has its own generated module,
// lib/content/terms.ts.
//
// DO NOT EDIT BY HAND -- regenerate from the spreadsheet instead.

export type CopyEntry = {
  readonly page: string;
  readonly type: string;
  readonly en: string;
  readonly fr: string;
};

export const COPY_FR: Readonly<Record<string, CopyEntry>> = {
''')
    for page, e in rows:
        out.write('  %s: {\n    page: "%s",\n    type: "%s",\n    en: "%s",\n    fr: "%s",\n  },\n'
                  % (e["id"], page, esc(e["type"]), esc(e["en"]), esc(e["fr"])))
    out.write('''};

/** Look up the approved French for an exact English string. */
export const FR_BY_ENGLISH: ReadonlyMap<string, string> = new Map(
  Object.values(COPY_FR).map((e) => [e.en, e.fr]),
);
''')
    io.open(OUT, "w", encoding="utf-8").write(out.getvalue())
    print("%d translated strings -> %s" % (len(rows), OUT))


if __name__ == "__main__":
    main()
