# -*- coding: utf-8 -*-
"""
Generate lib/content/copy.da.ts from Bjørn's PDF rather than the .xlsx.

The Danish first went live from the spreadsheet's DA column. Bjørn then sent a
PDF of his own workbook in which 51 of the 229 strings are rewritten -- not
corrections of mistakes, but a native speaker replacing serviceable Danish
with idiomatic Danish ("Det er Norsk hygge", "ud over vidderne"). His version
wins, so this reads the PDF.

Run _scripts/i18n/parse_da_pdf.py first; it writes _da_pdf.json.

Every row is checked against the English in the spreadsheet before it is used:
if the PDF's English for a T-id does not match, the tables are misaligned and
the run aborts rather than publishing Danish against the wrong sentence.
"""
import io
import json
import os
import re

import openpyxl

PDF_JSON = "_scripts/i18n/_da_pdf.json"
OUT = "lib/content/copy.da.ts"
SRC = os.path.join(
    r"C:\Users\Abbas\OneDrive\Desktop\noman",
    "REFUGE61_Website_V2_EN_FR_DA_FR_corrige.xlsx",
)
SHEET_PAGE = {
    "HOME": "home",
    "THE LODGE": "lodge",
    "PRACTICAL INFO": "practical",
    "LET'S TALK": "letsTalk",
    "NAVIGATION": "nav",
}


def norm(s):
    return re.sub(r"\s+", " ", (s or "")).strip()


def spreadsheet():
    wb = openpyxl.load_workbook(SRC)
    out = {}
    for name, page in SHEET_PAGE.items():
        if name not in wb.sheetnames:
            continue
        for r in wb[name].iter_rows(min_row=4, values_only=True):
            if not r or not r[0]:
                continue
            out[str(r[0]).strip()] = {
                "page": page,
                "type": norm(r[1]),
                "en": norm(r[2]),
            }
    return out


def esc(t):
    return t.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def main():
    pdf = json.load(io.open(PDF_JSON, encoding="utf-8"))
    sheet = spreadsheet()

    rows, mismatched = [], []
    for tid, meta in sheet.items():
        entry = pdf.get(tid)
        if not entry or not entry["da"]:
            continue
        # The PDF is a print of the same table; if its English disagrees, the
        # row is not the row we think it is.
        if norm(entry["en"]) != meta["en"]:
            mismatched.append(tid)
            continue
        rows.append((tid, meta, norm(entry["da"])))

    if mismatched:
        print("ABORTING -- English mismatch on %d row(s): %s"
              % (len(mismatched), ", ".join(mismatched[:12])))
        raise SystemExit(1)

    out = io.StringIO()
    out.write('''// Danish copy.
//
// Generated by _scripts/i18n/gen_copy_da.py from the PDF Bjørn sent on
// 2026-08-29 (parsed by parse_da_pdf.py), not from the .xlsx the French comes
// from: his PDF rewrites 51 of these strings into idiomatic Danish, and his
// version is the one to publish.
//
// Every row was checked against the spreadsheet's English before being
// written, so a Danish string cannot end up attached to the wrong sentence.
//
// Terms & Conditions are absent here: that page has its own module,
// lib/content/terms.ts.
//
// DO NOT EDIT BY HAND -- regenerate from the source documents instead.

export type CopyEntry = {
  readonly page: string;
  readonly type: string;
  readonly en: string;
  readonly tr: string;
};

export const COPY_DA: Readonly<Record<string, CopyEntry>> = {
''')
    for tid, meta, da in rows:
        out.write(
            '  %s: {\n    page: "%s",\n    type: "%s",\n    en: "%s",\n    tr: "%s",\n  },\n'
            % (tid, meta["page"], esc(meta["type"]), esc(meta["en"]), esc(da))
        )
    out.write('''};

/** Look up the approved Danish for an exact English string. */
export const DA_BY_ENGLISH: ReadonlyMap<string, string> = new Map(
  Object.values(COPY_DA).map((e) => [e.en, e.tr]),
);
''')
    io.open(OUT, "w", encoding="utf-8").write(out.getvalue())
    print("%d Danish strings -> %s" % (len(rows), OUT))


if __name__ == "__main__":
    main()
