# -*- coding: utf-8 -*-
"""
Regenerate lib/content/copy.<locale>.ts and the snapshot it was built from.

    python _scripts/i18n/gen_copy_fr.py fr
    python _scripts/i18n/gen_copy_fr.py da

Point SRC at the client's newest spreadsheet and run. The snapshot
(_client_fr.json) is committed so the next revision can be diffed against what
is actually live -- see diff_fr.py -- rather than against whichever file
happens to be in Downloads.

"""
import io
import json
import sys
import os
import re

import openpyxl

SRC = os.path.join(
    r"C:\Users\Abbas\OneDrive\Desktop\noman",
    "REFUGE61_Website_V2_EN_FR_DA_FR_corrige.xlsx",
)
SNAPSHOT = "_scripts/i18n/_client_fr.json"

# Which spreadsheet column holds each language.
COLUMN = {"fr": 3, "da": 4}

SHEET_PAGE = {
    "HOME": "home",
    "THE LODGE": "lodge",
    "PRACTICAL INFO": "practical",
    "LET'S TALK": "letsTalk",
    "TERMS": "terms",
    "NAVIGATION": "nav",
}


def clean(s):
    # The client types in Word; runs of whitespace and stray double spaces come
    # through with the text ("pendant  l'hiver 2027").
    return re.sub(r"\s+", " ", (s or "").strip())


def read(col):
    wb = openpyxl.load_workbook(SRC)
    sheets, rows = {}, []
    for name, page in SHEET_PAGE.items():
        if name not in wb.sheetnames:
            continue
        got = []
        for r in wb[name].iter_rows(min_row=4, values_only=True):
            if not r or not r[0]:
                continue
            entry = {
                "id": str(r[0]).strip(),
                "type": clean(r[1]),
                "en": clean(r[2]),
                "fr": clean(r[3]),
                "tr": clean(r[col]) if len(r) > col else "",
            }
            got.append(entry)
            if entry["en"] and entry["tr"]:
                rows.append((page, entry))
        sheets[name] = got
    return sheets, rows


def esc(t):
    return t.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def main():
    locale = sys.argv[1] if len(sys.argv) > 1 else "fr"
    if locale not in COLUMN:
        raise SystemExit("locale must be one of: %s" % ", ".join(COLUMN))
    out_path = "lib/content/copy.%s.ts" % locale
    upper = locale.upper()

    sheets, rows = read(COLUMN[locale])
    if locale == "fr":
        # The snapshot only tracks French, which is the column the client
        # revises round to round.
        json.dump({"sheets": sheets}, io.open(SNAPSHOT, "w", encoding="utf-8"),
                  ensure_ascii=False, indent=1)

    out = io.StringIO()
    out.write('''// %(upper)s copy, from the client's translation spreadsheet.
// Generated by _scripts/i18n/gen_copy_fr.py -- run it with the locale:
//     python _scripts/i18n/gen_copy_fr.py %(locale)s
//
// Keys are the T-ids from docs/_website-copy-EN.md, assigned by
// _scripts/extract-copy.mjs in document order. `en` is kept alongside `fr` so
// a string can be located in the JSX by exact match on the English; `tr`
// is the translation for this file's locale.
//
// Terms & Conditions are absent here: that page has its own generated module,
// lib/content/terms.ts.
//
// DO NOT EDIT BY HAND -- regenerate from the spreadsheet instead.

export type CopyEntry = {
  readonly page: string;
  readonly type: string;
  readonly en: string;
  readonly tr: string;
};

export const COPY_%(upper)s: Readonly<Record<string, CopyEntry>> = {
''' % {"upper": upper, "locale": locale})
    for page, e in rows:
        out.write('  %s: {\n    page: "%s",\n    type: "%s",\n    en: "%s",\n    tr: "%s",\n  },\n'
                  % (e["id"], page, esc(e["type"]), esc(e["en"]), esc(e["tr"])))
    out.write('''};

/** Look up the approved %(upper)s for an exact English string. */
export const %(upper)s_BY_ENGLISH: ReadonlyMap<string, string> = new Map(
  Object.values(COPY_%(upper)s).map((e) => [e.en, e.tr]),
);
''' % {"upper": upper})
    io.open(out_path, "w", encoding="utf-8").write(out.getvalue())
    print("%d translated strings -> %s" % (len(rows), out_path))


if __name__ == "__main__":
    main()
